[GENERAL]
COINS=BTC,ETH,LUNC,DOGE,PEOPLE,WING,CFX,BNB,APT,DOT,LDO,FTM,OP,DYDX,SHIB,LINK,XRP,AVAX,ICP,EOS,LTC,CRV,ADA,GALA,SAND,NEAR,MINA,AR,MATIC,FLOW,FXS,FET,CHZ,JASMY,GRT,FIL,ATOM,STORJ,LRC,HIGH,UNI,IMX,MANA,AAVE,GMT,ROSE,EGLD,COTI,XMR,KSM,OCEAN,HBAR,DASH,CELO,SUSHI,KAVA,RUNE,ZEC,ENS,SKL,BCH,TRX,GTC,1INCH,QNT,ONE,XLM,ENJ,ALICE,BAT,XTZ,ONT,COMP,IOTX,ARPA,BAND,RVN,APE,SFP,OMG,KNC,SOL,FLM,ANT,VET,AUDIO,AUD,BAL,CORE,IOST,COMP,LUNA,KAVA,TONCOIN,ANKR,SNX,RNDR,MASK,ASTR,OGN,ETC,AXS,ZIL,YFI,ALGO,THETA,OGN,ZRX,UNFI,GT,MKR,GAL,HOOK,MAGIC,PHB,WAVES
KEY=15bda010cb44c6696cbcaa8ffe228145e2946a1fa1b9aa640e75f5d5dfc51bcc
VIP=ETH,UNFI,SOL,WING,ADA
